matrix:
  include:

    language: android
    android:
      components:
        - build-tools-26.0.1
        - android-23


    language: python
    python:
      - "3.4"
      - "3.5"
      - "3.6"
    install: pip3 install "./server[test]"
    before_script: cd server
    script: tox
